/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PFaceDetection.java
 *
 * Created on Mar 22, 2012, 4:09:11 PM
 */
package com.bc5Neptune.cis.gui;

import static com.googlecode.javacv.cpp.opencv_core.*;
import static com.googlecode.javacv.cpp.opencv_imgproc.*;
import static com.googlecode.javacv.cpp.opencv_highgui.*;
import com.bc5Neptune.cis.bll.FaceDetection;
import static com.bc5Neptune.cis.bll.GlobalObject.*;
import com.bc5Neptune.cis.bll.IconList;
import com.bc5Neptune.cis.bll.ProcessFile;
import com.bc5Neptune.cis.bll.ProcessImage;
import com.bc5Neptune.cis.bll.ReadFolder;
import com.bc5Neptune.cis.bll.VerticalIconRender;
import com.googlecode.javacv.cpp.opencv_core.IplImage;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author phu.huynh
 */
public class PFaceDetection extends JPanel {
    /*
     * control disable or enable region
     */
    final int SORT_INCREASE = 1;
    boolean toggleRegion = false;
    /* save icon for list render */
    public ArrayList<IconList> iconTrainArr = new ArrayList<IconList>();
    /* save 10 faces to insert to database */
    public ArrayList<IconList> iconTempArr = new ArrayList<IconList>();
    
    public PFaceDetection() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooseFolder = new javax.swing.JFileChooser();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        btnOpenFolder = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        scrollPanelThumb = new javax.swing.JScrollPane();
        lstThumbnails = new javax.swing.JList();
        jPanel25 = new javax.swing.JPanel();
        splMain1 = new javax.swing.JSplitPane();
        jPanel26 = new javax.swing.JPanel();
        pnlShowImage = new javax.swing.JPanel();
        pnlFaceAnotations1 = new javax.swing.JPanel();
        scrollFaceImages = new javax.swing.JScrollPane();
        lstFaceImages = new javax.swing.JList();
        jPanel30 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jSplitPane6 = new javax.swing.JSplitPane();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        scrollTrainFace = new javax.swing.JScrollPane();
        lstTrainFace = new javax.swing.JList();
        jScrollBar5 = new javax.swing.JScrollBar();
        jPanel41 = new javax.swing.JPanel();
        cmbTrainFace = new javax.swing.JComboBox();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setName("Face Detection"); // NOI18N

        jSplitPane3.setDividerLocation(50);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel10.setBackground(java.awt.Color.lightGray);

        btnOpenFolder.setText("Open Folder");
        btnOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenFolder)
                .addContainerGap(512, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setTopComponent(jPanel10);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane3.setFocusable(false);

        jSplitPane4.setDividerLocation(150);

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder("Thumbnails"));

        lstThumbnails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lstThumbnails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstThumbnailsMouseClicked(evt);
            }
        });
        lstThumbnails.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstThumbnailsValueChanged(evt);
            }
        });
        scrollPanelThumb.setViewportView(lstThumbnails);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelThumb, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelThumb, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane4.setLeftComponent(jPanel22);

        splMain1.setDividerLocation(380);
        splMain1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnlShowImage.setBackground(new java.awt.Color(102, 102, 102));
        pnlShowImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlShowImage.setAlignmentX(0.0F);
        pnlShowImage.setAlignmentY(0.0F);
        pnlShowImage.setAutoscrolls(true);

        javax.swing.GroupLayout pnlShowImageLayout = new javax.swing.GroupLayout(pnlShowImage);
        pnlShowImage.setLayout(pnlShowImageLayout);
        pnlShowImageLayout.setHorizontalGroup(
            pnlShowImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        pnlShowImageLayout.setVerticalGroup(
            pnlShowImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlShowImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlShowImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        splMain1.setTopComponent(jPanel26);

        pnlFaceAnotations1.setBorder(javax.swing.BorderFactory.createTitledBorder("Face Anotations"));
        pnlFaceAnotations1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlFaceAnotations1.setMaximumSize(new java.awt.Dimension(594, 126));

        scrollFaceImages.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lstFaceImages.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        lstFaceImages.setName("listFace"); // NOI18N
        lstFaceImages.setVisibleRowCount(1);
        scrollFaceImages.setViewportView(lstFaceImages);

        javax.swing.GroupLayout pnlFaceAnotations1Layout = new javax.swing.GroupLayout(pnlFaceAnotations1);
        pnlFaceAnotations1.setLayout(pnlFaceAnotations1Layout);
        pnlFaceAnotations1Layout.setHorizontalGroup(
            pnlFaceAnotations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFaceImages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        pnlFaceAnotations1Layout.setVerticalGroup(
            pnlFaceAnotations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFaceImages, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        splMain1.setBottomComponent(pnlFaceAnotations1);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splMain1)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splMain1)
        );

        jSplitPane4.setRightComponent(jPanel25);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );

        jTabbedPane3.addTab("Image Brower", jPanel21);

        jSplitPane6.setDividerLocation(200);

        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder("Know Faces"));

        lstTrainFace.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollTrainFace.setViewportView(lstTrainFace);

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addComponent(scrollTrainFace, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTrainFace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addComponent(jScrollBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder("Person ID"));

        cmbTrainFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTrainFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addComponent(cmbTrainFace, 0, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addComponent(cmbTrainFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane6.setLeftComponent(jPanel39);

        jPanel43.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Original Image", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel19.setText("Click me to import a image");

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel19)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTextArea5.setColumns(10);
        jTextArea5.setRows(3);
        jTextArea5.setTabSize(5);
        jScrollPane14.setViewportView(jTextArea5);

        jLabel20.setText("Full name:");

        jLabel21.setText("Person ID:");

        jTextArea6.setColumns(10);
        jTextArea6.setRows(3);
        jTextArea6.setTabSize(5);
        jScrollPane15.setViewportView(jTextArea6);

        jLabel22.setText("Hometown:");

        jLabel23.setText("Birthday:");

        jLabel24.setText("People:");

        jLabel25.setText("Place of residence:");

        txtID.setText("205507914");

        jLabel26.setText("Religious:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton17.setText("Reset");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22)
            .addComponent(jLabel25)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(4, 4, 4)
                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField17, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(25, 25, 25)
                        .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel21))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel23))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel22)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel24))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel26))
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton17)))
        );

        jLabel27.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel27.setText("INFORMATION");

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel27)))
                .addContainerGap())
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(36, 36, 36)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane6.setRightComponent(jPanel42);

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane6)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane6)
        );

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Face Database", jPanel30);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane3))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void choseFolder() {
        fileChooseFolder.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = fileChooseFolder.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File folderSelected = fileChooseFolder.getSelectedFile();
            final String folder = folderSelected.getAbsolutePath() + "/";
            System.out.println(folder);

            lstThumbnails.setCellRenderer(null); //clear cell render

            final ReadFolder readFolder = new ReadFolder(folder, "image");
            String[] files = readFolder.read(SORT_INCREASE);
            // init value for ImageList 
            GLImageList.setFileImages(files);
            GLImageList.setPathFolder(folder);
            /*
             * thread to read the images
             */
            new Thread() {

                public void run() {
                    GLImageList.cvload();
                    //resize image 90 X 120
                    int length = GLImageList.getLength(); //length of array images
                    if (length > 0) {
                        IconList[] iconList = new IconList[length];
                        /*
                         * inilization a object of icon class show it in a
                         * listbox
                         */
                        for (int i = 0; i < length; i++) {
                            iconList[i] = new IconList(GLImageList.getFileNames(i), //name of a image
                                    GLImageList.getImageList(i),//buffer of a image
                                    120, //width
                                    90); //height
                        }

                        /*
                         * set value of render
                         */
                        lstThumbnails = new JList(iconList);
                        VerticalIconRender renderer = new VerticalIconRender();
                        lstThumbnails.setCellRenderer(renderer);
                    }
                    /*
                     * clear pnlShowImage and list face
                     */
                    pnlShowImage.revalidate();
                    pnlShowImage.repaint();

                    /*
                     * set event click
                     */
                    lstThumbnails.addMouseListener(new ListImageListener());
                    /*
                     * add jlist on scrollPanel
                     */
                    scrollPanelThumb.setViewportView(lstThumbnails);
                    
                    /* init face region */
                    GLPCustom.positionArr = new FaceRegion[GLImageList.getLength()];
                    interrupt();
                }
                /*
                 * show the images in list
                 */
            }.start();
        }
    }
    private void btnOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFolderActionPerformed

        choseFolder();
    }//GEN-LAST:event_btnOpenFolderActionPerformed

    private void cmbTrainFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTrainFaceActionPerformed
        // TODO add your handling code here:
        //empty arrTemplist
        iconTempArr.clear();
        
        System.out.println("You chose me" + cmbTrainFace.getSelectedItem());
        String currentNameSelect = (String) cmbTrainFace.getSelectedItem();
        for(int i = 0 ; i < iconTrainArr.size(); i++){
            IconList icon = iconTrainArr.get(i);
            if (icon.getName().equalsIgnoreCase(currentNameSelect)){
                iconTempArr.add(icon);
            }
        }
        //set list cell render
        lstTrainFace = new JList(iconTempArr.toArray());
        VerticalIconRender render = new VerticalIconRender();
        lstTrainFace.setCellRenderer(render);
        scrollTrainFace.setViewportView(lstTrainFace);
        //repaint list
        lstTrainFace.revalidate();
        lstTrainFace.repaint();
    }//GEN-LAST:event_cmbTrainFaceActionPerformed

    private void lstThumbnailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstThumbnailsMouseClicked
        // TODO add your handling code here:
        System.out.println(lstThumbnails.getSelectedIndex());
        //set cellrender again
        
    }//GEN-LAST:event_lstThumbnailsMouseClicked

    private void lstThumbnailsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstThumbnailsValueChanged
        // TODO add your handling code here:
        System.out.println("Hele");
    }//GEN-LAST:event_lstThumbnailsValueChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int NUM_ARRAY = 10;
        System.out.println("click save");
        BufferedImage[] imagesArr = new BufferedImage[NUM_ARRAY];
        if (iconTempArr.size() == 10){
            ProcessFile proFile = new ProcessFile();
            //IconList[] iconArr = lstTrainFace.getCellRenderer();
            
           for(int i = 0; i < NUM_ARRAY; i++){
               IconList icon = iconTempArr.get(i);
               imagesArr[i] = icon.getImage();
           }
           //change to gray image
           ProcessImage proImage = new ProcessImage();
           //create folder tmp
           proFile.createFolder("../CIS_SProjectR2/data/tmp/");
           for(int i = 0; i < NUM_ARRAY; i++){
               IplImage cvImage = new IplImage();
               cvImage = IplImage.createFrom(imagesArr[i]);
               cvImage = proImage.setGray(cvImage);
               cvSaveImage("../CIS_SProjectR2/data/tmp/" + (i + 1) + ".pgm", cvImage);
           }
           //for(int i = 0; i <)
           proFile.createDatFile(txtID.getText());
           proFile.deleteFolder("../CIS_SProjectR2/data/tmp/");
           
           //proFile.saveBuffImageToDAT(imagesArr, txtID.getText(),"../CIS_SProjectR2/data/facedat/");
           System.out.println("Save array of images to dat successfully");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenFolder;
    private javax.swing.JButton btnSave;
    public javax.swing.JComboBox cmbTrainFace;
    private javax.swing.JFileChooser fileChooseFolder;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JScrollBar jScrollBar5;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField7;
    public javax.swing.JList lstFaceImages;
    public javax.swing.JList lstThumbnails;
    public javax.swing.JList lstTrainFace;
    private javax.swing.JPanel pnlFaceAnotations1;
    public javax.swing.JPanel pnlShowImage;
    public javax.swing.JScrollPane scrollFaceImages;
    private javax.swing.JScrollPane scrollPanelThumb;
    public javax.swing.JScrollPane scrollTrainFace;
    private javax.swing.JSplitPane splMain1;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}

class ListImageListener extends MouseAdapter {

    JPopupMenu rightMenu = new JPopupMenu("Right menu");

    public ListImageListener() {

        /*
         * Enable Region menu
         */
        JMenuItem enableRegion = new JMenuItem("Enable Region");
        //addMenu.setIcon(getIcon("../CIS_SProjectR2/src/icon/Delete_16x16.png"));
        enableRegion.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Enable Region");
                GLPDetect.toggleRegion = true;
                GLPDetect.pnlShowImage.revalidate();
                GLPDetect.pnlShowImage.repaint();
            }
        });


        rightMenu.add(enableRegion);
        /*
         * Disable Region menu
         */
        JMenuItem disableRegion = new JMenuItem("Disable Region");
        //disableRegion.setIcon(getIcon("../CIS_SProjectR2/src/icon/Delete_16x16.png"));
        disableRegion.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                GLPDetect.toggleRegion = false;
                GLPDetect.pnlShowImage.revalidate();
                GLPDetect.pnlShowImage.repaint();
                System.out.println("Disable Region");

            }
        });
        rightMenu.add(disableRegion);

        /*
         * Detect This Face menu
         */
        JMenuItem detectFace = new JMenuItem("Detect This Image");
        //disableRegion.setIcon(getIcon("../CIS_SProjectR2/src/icon/Delete_16x16.png"));
        detectFace.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                final int index = GLPDetect.lstThumbnails.getSelectedIndex();
                if (index >= 0) {
                    new Thread() {

                        @Override
                        public void run() {
                            FaceDetection objDetect = new FaceDetection();
                            IplImage image = GLImageList.cvImagesArr[index];
                            objDetect.detectFace(image, index);
                            System.out.println("Detect This Face");
                            GLPCustom.updateListFace();
                            interrupt();
                        }
                    }.start();

                }
            }
        });
        rightMenu.add(detectFace);

        /*
         * Detect All Faces menu
         */
        JMenuItem detectAllFaces = new JMenuItem("Detect All of Images");
        //disableRegion.setIcon(getIcon("../CIS_SProjectR2/src/icon/Delete_16x16.png"));
        detectAllFaces.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                final int index = GLPDetect.lstThumbnails.getSelectedIndex();
                if (index >= 0) {
                    new Thread() {

                        @Override
                        public void run() {
                          
                            System.out.println("Detect All Face Start");
                            FaceDetection objDetect = new FaceDetection();
                            IplImage[] images = GLImageList.cvImagesArr;
                            objDetect.detectFaces(images);

                            GLPCustom.updateListFace();
                            System.out.println("Detect All Face Finished");
                            interrupt();
                        }
                    }.start();

                }

            }
        });
        rightMenu.add(detectAllFaces);
        

    }
    /*
     * set icon for right click menu
     */

    public ImageIcon getIcon(String path) {
        ImageIcon icon = new ImageIcon(path);
        return icon;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        switch (e.getModifiers()) {
            case InputEvent.BUTTON1_MASK: {
                if (e.getClickCount() == 2) {
                    /*
                     * double click
                     */
                    if ( GLImageList.getLength() > 0) {
                        int index = 0;

                        ProcessImage objImg = new ProcessImage();
                       index = GLPDetect.lstThumbnails.getSelectedIndex();
                       BufferedImage image = objImg.resize(
                                GLImageList.getImageList(index),
                                GLPDetect.pnlShowImage.getWidth(),
                                GLPDetect.pnlShowImage.getHeight());

                        
                        /*
                         * check region on a image
                         */
                        if (GLPCustom.positionArr[index] == null) {
                            /*
                             * if not exist
                             */
                           GLPCustom.positionArr[index] = new FaceRegion();
                        }
                        /*
                         * if exist
                         */
                        GLPCustom.index = index;
                        GLPCustom.image = image;
                        GLPCustom.fileName = GLImageList.getFileNames(index);

                        
                        GLPDetect.pnlShowImage.setLayout(new BoxLayout(GLPDetect.pnlShowImage, BoxLayout.PAGE_AXIS));

                        GLPDetect.pnlShowImage.repaint(); //repaint a image
                        GLPDetect.pnlShowImage.revalidate(); //clear
                        GLPDetect.pnlShowImage.add(GLPCustom);
                    }
                }
                break;
            }
            case InputEvent.BUTTON2_MASK: {

                System.out.println("That's the MIDDLE button");

                break;
            }
            case InputEvent.BUTTON3_MASK: {
                System.out.println("That's the RIGHT button");
                //rightMenu.pack();
                rightMenu.show(e.getComponent(), e.getX(), e.getY());
                break;
            }
        }
    }
}
