/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PFaceRecognition.java
 *
 * Created on Mar 23, 2012, 9:58:00 AM
 */
package com.bc5Neptune.cis.gui;

import static com.bc5Neptune.cis.bll.GlobalObject.*;
import static com.bc5Neptune.cis.bll.GlobalObject.*;
import com.bc5Neptune.cis.bll.FaceRecognition;
import com.bc5Neptune.cis.bll.GlobalObject;
import com.bc5Neptune.cis.bll.VerticalIconRender;
import com.bc5Neptune.cis.bll.ReadFolder;
import com.bc5Neptune.cis.bll.IconList;
import com.bc5Neptune.cis.bll.ProcessFile;
import com.bc5Neptune.cis.config.Config;
import com.bc5Neptune.cis.entity.PersonEntity;
import com.bc5Neptune.cis.dal.PersonDAL;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTabbedPane;
import javax.swing.border.EmptyBorder;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author phu.huynh
 */
public class PFaceRecognition extends JPanel {
    /* array of face of images */

    public ArrayList<BufferedImage> listFace = new ArrayList<BufferedImage>();
    /* array for list cell render */
    public ArrayList< IconList> objSmall = new ArrayList<IconList>();
    /* vertical cell render */
    private VerticalIconRender render;

    /** Creates new form PFaceRecognition */
    public PFaceRecognition() {
        initComponents();
    }

    public int getLength() {
        return listFace.size();
    }

    /* get image from index */
    public BufferedImage getBufferedImage(int index) {
        return listFace.get(index);
    }

    public void updateListFace() {
        //
        int length = getLength();
        //if (getLength() > 0) {
        // objSmall = new SmallImage[length];
        //for (int i = obj; i < length; i++) {
        //  objSmall[i] = new SmallImage("unknow", getBufferedImage(i), 92, 112);
        //}
        lstFace = new JList(objSmall.toArray());
        render = new VerticalIconRender();
        lstFace.setCellRenderer(render);
        scrollPane.setViewportView(lstFace);
        lstFace.addMouseListener(new RecognitionListener());
        //}

        // if (lstFace.size())
        // SmallImage objSmall = new SmallImage(TOOL_TIP_TEXT_KEY, null, WIDTH, WIDTH)
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        lstFace = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        tabFaceNearist = new javax.swing.JTabbedPane();

        setName("Face Recognition"); // NOI18N

        jSplitPane1.setDividerLocation(50);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(java.awt.Color.lightGray);

        jButton1.setText("Import Faces");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(685, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jPanel1);

        jSplitPane2.setDividerLocation(200);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Face List"));

        scrollPane.setViewportView(lstFace);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        jPanel4.setBackground(java.awt.Color.lightGray);

        tabFaceNearist.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFaceNearist, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(tabFaceNearist, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JList lstFace;
    private javax.swing.JScrollPane scrollPane;
    public javax.swing.JTabbedPane tabFaceNearist;
    // End of variables declaration//GEN-END:variables
}

class RecognitionListener extends MouseAdapter {

    JPopupMenu rightMenu = new JPopupMenu("Right menu");

    /**
     * add button tab to JTabbedPane
     * @param nameLabel     a name of tab
     * @param action        a action when click on it
     * @param pane          a JPanel that you want add to tab
     * @param tabPane       a JTabbedPane that you want JPanel add on it
     */
    public void addTab(final String nameLabel,
            final String action,
            final JPanel pane,
            final JTabbedPane tabPane) {
        /* add JPanel to JTabedPane */
        for (int i = 0; i < tabPane.getComponentCount(); i++) {
            final JPanel pn = (JPanel) tabPane.getComponent(i);
            if (pn.getName() != null) {
                if (pn.getName().equals(pane.getName())) {
                    System.out.println("This panel is exist");
                    /* show to exist tab */
                    tabPane.setSelectedComponent(pn);
                    return;
                }
            }

        }

        tabPane.add(pane);
        /* create button to close tab*/
        final JButton tabCloseButton = new JButton("X");
        /* set border for button */
        tabCloseButton.setBorder(new EmptyBorder(0, 0, 0, 0));
        /* set string for action command*/
        tabCloseButton.setActionCommand(action);

        /* add a button and a label to JPanel (pane) */
        final JPanel pnlAdd = new JPanel();
        pnlAdd.setPreferredSize(new Dimension(100, 20));
        pnlAdd.setOpaque(false);

        /* add a label */
        final JLabel lb = new JLabel(nameLabel);
        lb.setBorder(new EmptyBorder(0, 0, 0, 0));
        pnlAdd.add(lb);
        /* add a close button */
        pnlAdd.add(tabCloseButton);

        /* resize pnlAdd */
        // pnlAdd.setPreferredSize(new Dimension(lb.getPreferredSize().width + 23, 20));

        /* add JPanel in to tab */
        tabPane.setTabComponentAt(tabPane.getTabCount() - 1, pnlAdd);
        tabPane.setSelectedIndex(tabPane.getTabCount() - 1);

        /* create Action listener */
        ActionListener al;
        al = new ActionListener() {

            @Override
            public void actionPerformed(final ActionEvent e) {
                JButton button = (JButton) e.getSource();
                /* get action command */
                final String s1 = button.getActionCommand();
                /* find current tab and close it */
                for (int i = 0; i < tabPane.getTabCount(); i++) {
                    final JPanel pnl = (JPanel) tabPane.getTabComponentAt(i);
                    button = (JButton) pnl.getComponent(1); //The zero(0) is a label
                    //the first(1) is a button
                    final String s2 = button.getActionCommand();
                    /* check action command and close tab */
                    if (s1.equals(s2)) {
                        tabPane.removeTabAt(i);
                        break;
                    }
                }
            }
        };
        /* set action listener for close button */
        tabCloseButton.addActionListener(al);
    }

    public RecognitionListener() {


        /*
         * Enable Region menu
         */
        JMenuItem enableRegion = new JMenuItem("Recognition this face");
        //addMenu.setIcon(getIconResize("../CIS_SProjectR2/src/icon/Delete_16x16.png"));

        enableRegion.addActionListener(
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println("Recognition this face");

                        //call recognition

                        int index = GLPReg.lstFace.getSelectedIndex();

                        BufferedImage image = GLPReg.objSmall.get(index).getImage();

                        GLReg.recognizeFile(image);
                        //JList lstFaceNearist = new JList();
                        // JPanel panel = new JPanel();
                        //panel.add(lstFaceNearist);

                        IconList objSmall = (IconList) GLPReg.lstFace.getSelectedValue();
                        String str = objSmall.getName();

                        System.out.println(".................." + str);
                        final PPersonInformation personInfor = new PPersonInformation();
                        // add infor into list
                        //Object obj = GLReg.listIDPicture.toArray();
                        personInfor.listNearestPerson.setListData(GLReg.listNearestPerson.toArray());
                        ProcessFile prFile = new ProcessFile();

                        //get image into listicon 
                        int length = GLReg.listIDPicture.size();
                        IconList[] iconArr = new IconList[length];
                        for (int i = 0; i < length; i++) {
                            String name = GLReg.listNearestPerson.get(i);
                            int idPicture = GLReg.listIDPicture.get(i).intValue();
                            System.out.println("-----------------------Name = " + name + "Id = " + idPicture);
                            BufferedImage imageIcon = prFile.loadBufferedFace("../CIS_SProjectR2/data/facedat/",
                                    name, idPicture);
                            iconArr[i] = new IconList(name, imageIcon, 50, 70);
                        }



                        // iconArr[0] = new IconList("Recognition", imageIcon, 20, 30);
                        personInfor.listNearestPerson = new JList(iconArr);

                        VerticalIconRender render = new VerticalIconRender();
                        personInfor.listNearestPerson.setCellRenderer(render);
                        addTab(str, str, personInfor, GLPReg.tabFaceNearist);
                        personInfor.scrollPanel.setViewportView(personInfor.listNearestPerson);
                        personInfor.listNearestPerson.addMouseListener(new MouseAdapter() {

                            @Override
                            public void mouseClicked(MouseEvent ev) {
                                if (ev.getClickCount() == 2) {
                            try {
                                int a = personInfor.listNearestPerson.getSelectedIndex();
                                System.out.println("index" + a);
                                String tmp = GLReg.listNearestPerson.get(a).toString();
                                //IconList icon = (IconList) personInfor.listNearestPerson.getSelectedValue();
                                //System.out.println("icon .. " + icon.getName());
                                System.out.println("Double me!" + tmp);
                                String pid = tmp.substring(0, 9);
                                System.out.println("PID! " + pid);
                                //System.out.println(new PersonDAL().Select(pid).getFULLNAME());
                                personInfor.txfFullName.setText(new PersonDAL().Select(pid).getFullname());
                                personInfor.txfPID.setText(new PersonDAL().Select(pid).getPid());
                                personInfor.txfDOB.setText(new PersonDAL().Select(pid).getDob().toString());
                                personInfor.txfhometown.setText(new PersonDAL().Select(pid).getHometown());
                                personInfor.txfResidence.setText(new PersonDAL().Select(pid).getPermanent_residence());
                                personInfor.txfEthnic.setText(new PersonDAL().Select(pid).getEthnic());
                                personInfor.txfReligion.setText(new PersonDAL().Select(pid).getReligion());
                                personInfor.lblImage.setIcon(new ImageIcon(ImageIO.read(new PersonDAL().Select(pid).getImage().getBinaryStream())));
//                                JFrame f = new JFrame();
//                                JLabel lbl = new JLabel();
//                                lbl.setIcon(new ImageIcon(ImageIO.read(new PersonDAL().Select(pid).getImage().getBinaryStream())));
//                                f.add(lbl);
//                                f.setVisible(true);
//                                f.setSize(1000,1000);                                
                            } catch (IOException ex) {
                                Logger.getLogger(RecognitionListener.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (SQLException ex) {
                                Logger.getLogger(RecognitionListener.class.getName()).log(Level.SEVERE, null, ex);
                            }

                                }
                            }
                        });




                    }
                });


        rightMenu.add(enableRegion);
        /*
         * Disable Region menu
         */
        JMenuItem disableRegion = new JMenuItem("Recognition all of faces");
        //disableRegion.setIcon(getIconResize("../CIS_SProjectR2/src/icon/Delete_16x16.png"));

        disableRegion.addActionListener(
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {

                        System.out.println("Recognition all of faces");

                    }
                });
        rightMenu.add(disableRegion);

        /*
         * Detect This Face menu
         */
        JMenuItem detectFace = new JMenuItem("Delete this image");
        //disableRegion.setIcon(getIconResize("../CIS_SProjectR2/src/icon/Delete_16x16.png"));

        detectFace.addActionListener(
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println("Delete this image");
                        int index = GLPReg.lstFace.getSelectedIndex();
                        if (index >= 0) {
                            GLPReg.objSmall.remove(index);
                            GLPReg.lstFace.repaint();
                            GLPReg.lstFace.revalidate();
                            GLPReg.updateListFace();
                        }

                    }
                });
        rightMenu.add(detectFace);

        /*
         * Detect All Faces menu
         */
        JMenuItem detectAllFaces = new JMenuItem("Delete All of faces");
        //disableRegion.setIcon(getIconResize("../CIS_SProjectR2/src/icon/Delete_16x16.png"));

        detectAllFaces.addActionListener(
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int count = GLPReg.objSmall.size();
                        while (count > 0) {
                            GLPReg.objSmall.remove(0);
                            GLPReg.lstFace.repaint();
                            GLPReg.lstFace.revalidate();
                            count = GLPReg.objSmall.size();
                            GLPReg.updateListFace();
                        }
                        System.out.println("Delete all of faces");
                    }
                });
        rightMenu.add(detectAllFaces);
    }
    /*
     * set icon for right click menu
     */

    public ImageIcon getIcon(String path) {
        ImageIcon icon = new ImageIcon(path);
        return icon;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        switch (e.getModifiers()) {
            case InputEvent.BUTTON1_MASK: {
                if (e.getClickCount() == 2) {
                    /*
                     * double click
                     */
//                    PFaceDetection objTmp = PFaceDetection.getInstance();
//                    if (objTmp.objImglist.getLength() > 0) {
//                        int index = 0;
//
//                        ProcessImage objImg = new ProcessImage();
//                        index = objTmp.lstThumbnails.getSelectedIndex();
//                        BufferedImage tmpBuffer = objImg.scaleImg(
//                                objTmp.objImglist.getImagesBuffered(index),
//                                objTmp.pnlShowImage.getWidth(),
//                                objTmp.pnlShowImage.getHeight());
//
//                        /*
//                         * check region on a image
//                         */
//                        if (PDrawPanel.getInstance().position[index] == null) {
//                            /*
//                             * if not exist
//                             */
//                            PDrawPanel.getInstance().position[index] = new Region();
//                        }
//                        /*
//                         * if exist
//                         */
//                        PDrawPanel.getInstance().index = index;
//                        PDrawPanel.getInstance().image = tmpBuffer;
//                        PDrawPanel.getInstance().fileName = objTmp.objImglist.getFileNames(index);
//
//                        objTmp.dPanel = PDrawPanel.getInstance();
//                        objTmp.pnlShowImage.setLayout(new BoxLayout(objTmp.pnlShowImage, BoxLayout.PAGE_AXIS));
//
//                        //objTmp.pnlShowImage.removeAll(); //delete previous image
//                        objTmp.pnlShowImage.repaint(); //repaint a image
//                        objTmp.pnlShowImage.revalidate(); //clear
//                        objTmp.pnlShowImage.add(objTmp.dPanel);
//                    }
                }
                break;
            }
            case InputEvent.BUTTON2_MASK: {

                System.out.println("That's the MIDDLE button");

                break;
            }
            case InputEvent.BUTTON3_MASK: {
                System.out.println("That's the RIGHT button");
                //rightMenu.pack();
                rightMenu.show(e.getComponent(), e.getX(), e.getY());
                break;
            }
        }
    }
}