<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
<soap:Header>
</soap:Header>
<soap:Body>
<webs:login xmlns:webs="http://webservices.login.jboss.org/">
<!-- optional -->
<arg0>plato</arg0>
<!-- optional -->
<arg1>1234</arg1>
</webs:login>
</soap:Body>
</soap:Envelope>